version: 2.1
orbs:
  win: circleci/windows@2.2.0
jobs:
  build-win:
    executor:
      name: win/default
      shell: powershell.exe
    working_directory: /app
    steps:
      - checkout
      - run: npm install
      - run: npm run make
      - run: ren /app/out/make/zip/win32/x64/magnum-opus-launcher-win32-* /app/out/make/zip/win32/x64/magnum-opus-launcher.zip
      - store_artifacts:
          path: /app/out/make/zip/win32/x64/magnum-opus-launcher.zip
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-win:
          filters:
            branches:
              only: master
