version: 2.1
orbs:
  win: circleci/windows@2.2.0
jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    working_directory: ~/app
    steps:
      - checkout
      - run: npm install
      - run: npm run make
      - store_artifacts:
          path: /out
