version: 2.1
orbs:
  win: circleci/windows@2.2.0
  aws-s3: circleci/aws-s3@1.1.0
jobs:
  build-win:
    executor:
      name: win/default
      shell: powershell.exe
    working_directory: /app
    steps:
      - checkout
      - run: npm install
      - run: npm run make
      - run: cd /app/out/make/zip/win32/x64; ren * magnum-opus-launcher.zip
#      - store_artifacts:
#          path: /app/out/make/zip/win32/x64/magnum-opus-launcher.zip
      - aws-s3/copy:
          arguments: '--dryrun'
          from: /app/out/make/zip/win32/x64/magnum-opus-launcher.zip
          to: s3://magnum-opus-launcher/windows
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-win:
          filters:
            branches:
              only: master
